In [2]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics


In [3]:
pro = pd.read_csv('Product.csv')

In [4]:
df = pd.DataFrame(pro)

In [5]:
X = df.iloc[:,[2,3]].values
y = df.iloc[:,-1].values

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y)
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [14]:
model = RandomForestClassifier(n_estimators = 10,max_leaf_nodes =10)
model.fit(X_train,y_train)

RandomForestClassifier(max_leaf_nodes=10, n_estimators=10)

In [15]:
y_pred = model.predict(X_test)

In [16]:
y_pred

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0], dtype=int64)

In [17]:
y_test

array([0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0], dtype=int64)

In [18]:
print(metrics.confusion_matrix(y_pred,y_test))


[[59  2]
 [ 5 34]]


In [20]:
print(metrics.accuracy_score(y_pred,y_test))

0.93
